version: 1.0.{build}

image: Visual Studio 2022

platform: x64
configuration: Release

skip_branch_with_pr: true

branches:
  only:
    - main
    - /feat\/.*/
    - /fix\/.*/

environment:
  VCPKG_ROOT: C:\Tools\vcpkg
  VCPKG_DEFAULT_TRIPLET: x64-windows-static
  VCPKG_BUILD_TYPE: release
  VCPKG_INSTALLED_DIR: C:\projects\forgottenserver-downgrade-1.8-8.60\vcpkg_installed\x64-windows-static

cache:
  - C:\Tools\vcpkg\installed
  - C:\Tools\vcpkg\downloads
  - C:\Tools\vcpkg\buildtrees

install:
  - cmd: git fetch --tags --force
  - cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: cmake --version
  - cmd: ninja --version
  - cmd: "%VCPKG_ROOT%\vcpkg.exe" version

build_script:
  - cmd: call "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=cl -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DBUILD_TESTING=OFF -DENABLE_ASAN=OFF
  - cmd: cmake --build build --config Release --parallel

test: off

artifacts:
  - path: build\tfs.exe
    name: tfs-windows-x64
  - path: vcpkg\buildtrees\**\*.log
    name: vcpkg-logs
