name: Build with vcpkg

concurrency:
  group: build-vcpkg-${{ github.workflow_ref }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'fix/**'
      - 'feat/**'

    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

  pull_request:
    paths:
      - .github/workflows/build-vcpkg.yml
      - cmake/**
      - src/**
      - CMakeLists.txt
      - CMakePresets.json
      - vcpkg.json

  workflow_dispatch:

jobs:
  build-windows:
    name: Windows
    runs-on: windows-2022

    env:
      VCPKG_BUILD_TYPE: release
      VCPKG_INSTALLED_DIR: ${{ github.workspace }}/vcpkg_installed/x64-windows-static-release
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg_cache
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite
      SCCACHE_GHA_ENABLED: "true"

    steps:
      - uses: actions/checkout@v7

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
        with:
          arch: x64

      - name: Create vcpkg binary cache directory
        run: mkdir -p "${{ github.workspace }}/vcpkg_cache"
        shell: bash

      - name: Get latest CMake
        uses: lukka/get-cmake@v4.3.4

      - name: Cache vcpkg binary packages
        uses: actions/cache@v5
        with:
          path: ${{ github.workspace }}/vcpkg_cache
          key: vcpkg-windows-${{ hashFiles('vcpkg.json', 'CMakeLists.txt', '**/CMakeLists.txt', 'CMakePresets.json') }}
          restore-keys: |
            vcpkg-windows-

      - name: Run vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696

      - name: Build with CMake
        uses: lukka/run-cmake@v10.9
        with:
          configurePreset: vcpkg
          buildPreset: vcpkg
          configurePresetAdditionalArgs: "['-GNinja', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_C_COMPILER=cl', '-DCMAKE_CXX_COMPILER=cl', '-DCMAKE_C_COMPILER_LAUNCHER=sccache', '-DCMAKE_CXX_COMPILER_LAUNCHER=sccache', '-DVCPKG_TARGET_TRIPLET=x64-windows-static', '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded']"

      - name: Upload build logs
        uses: actions/upload-artifact@v7
        with:
          name: logs-windows-${{ github.sha }}
          path: ${{ github.workspace }}/vcpkg/buildtrees/**/*.log
        if: ${{ failure() }}

      - name: Upload artifact binary
        uses: actions/upload-artifact@v7
        with:
          name: tfs-windows-${{ github.sha }}
          path: ${{ github.workspace }}/build/tfs.exe
