name: Build Docker Image (Linux)

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .dockerignore
      - ".github/workflows/docker-image.yml"
      - "src/**"
      - "cmake/**"
      - "data/**"
      - "vc18/**"
      - CMakeLists.txt
      - vcpkg.json
      - vcpkg-configuration.json

  pull_request:
    branches:
      - main
    paths:
      - Dockerfile
      - .dockerignore
      - ".github/workflows/docker-image.yml"
      - "src/**"
      - "cmake/**"
      - "data/**"
      - "vc18/**"
      - CMakeLists.txt
      - vcpkg.json
      - vcpkg-configuration.json

  workflow_dispatch:

concurrency:
  group: docker-image-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-24.04
    timeout-minutes: 60

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Docker version
        run: docker version

      - name: Build Docker image
        run: |
          docker build \
            --pull \
            --file ./Dockerfile \
            --tag tfs-linux:latest \
            .
